### ISSUE TITLE
Ошибка при парсинге.

### ISSUE THREAD

**Issue by grandmaster8** [evgkul/moonscript-opencomputers#3]
`func_b = ->
	value = 100
	print "The value:", value
`

Не хочет парсить такую конструкцию.

**Comment by grandmaster8** [comment]
Понятно, оказывается нужно было перезапустить компьютер, видимо в окружение ошибка.

**Comment by evgkul** [comment]
Все вопросы к авторам MoonScript, я просто отвязал его от использования debug при помощи костыля
